StreamMux: Disable buffering when reading FIFOs + handle .read() -> None
We've seen a single case of this error:

    ...
    File "./asyncjobs/stream_mux.py", line 89, in __exit__
      self.close()
    File ".and/asyncjobs/stream_mux.py", line 82, in close
      self.mux.unwatch(self.path)
    File "./asyncjobs/stream_mux.py", line 172, in unwatch
      self._do_read(f, decorator, buffer, last=True)
    File "./asyncjobs/stream_mux.py", line 155, in _do_read
      buffer.extend(f.read())
  TypeError: 'NoneType' object is not iterable

which indicates that f.read() may occasionally return None. This is not
documented as something io.BufferedReader.read() should ever do, but
according to https://bugs.python.org/issue13322 there are bugs in
Python's handling of non-blocking I/O where the behavior of the
underlying RawIOBase object will shine through. In any case, that bug
contains several warnings against combining buffered I/O objects and
non-blocking file descriptors, so we're surely better off using raw/
unbuffered I/O instead.

Disable buffering by passing buffering=0 to open() when we open the FIFO
for reading, and handle the possibility of .read() returning None.